id: ICB7D066B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T00:10:09+00:00'
last_modified: '2022-06-08T08:35:11.019212+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22250
  title: གསུང་འབུམ། འཇིགས་མེད་འཕྲིན་ལས་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    2C77:
      image_group_id: I5281
      title: ''
      total_pages: 864
      order: 1
      base_file: 2C77.txt
    '4315':
      image_group_id: I5282
      title: ''
      total_pages: 830
      order: 2
      base_file: 4315.txt
    37D4:
      image_group_id: I5283
      title: ''
      total_pages: 868
      order: 3
      base_file: 37D4.txt
    42EB:
      image_group_id: I5284
      title: ''
      total_pages: 828
      order: 4
      base_file: 42EB.txt
    1CFB:
      image_group_id: I5285
      title: ''
      total_pages: 816
      order: 5
      base_file: 1CFB.txt
    00AF:
      image_group_id: I5286
      title: ''
      total_pages: 856
      order: 6
      base_file: 00AF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
